[package]
name = "openntx-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
description = "Core models and planning logic for the OpenNTX experimental Windows application subsystem for Linux."
license-file = "../../LICENSE"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
sha2 = { workspace = true }
thiserror = { workspace = true }
tar = { workspace = true }
flate2 = { workspace = true }
dirs.workspace = true
inotify.workspace = true
libc.workspace = true
toml.workspace = true
anyhow = "1.0.102"

[dev-dependencies]
tempfile = "3"
